// Generated by CoffeeScript 1.9.1
(function() {
  var angular, ngModule;

  angular = require('angular');

  ngModule = angular.module('app', ['ui.router']);

  ngModule.config(function($urlRouterProvider, $rootScope) {
    $urlRouterProvider.otherwise("/inventory");
    return $rootScope.$on('stateChangeError', function(event, toState, toParams, fromState, fromParams, error) {
      return console.log(event, toState, toParams, fromState, fromParams, error);
    });
  });

  ngModule.run(function() {});

}).call(this);
